### ISSUE TITLE
Failed to activate the easy-motion package

### ISSUE THREAD

**Issue by AndrewRademacher** [adrian-budau/easy-motion#11]
[Enter steps to reproduce below:]
1. Hit Command-Shift-E

**Atom Version**: 0.187.0
**System**: Mac OS X 10.10.2
**Thrown From**: [easy-motion](https://github.com/adrian-budau/easy-motion) package, v1.1.4
### Stack Trace

Failed to activate the easy-motion package

```
At The `::command` method is no longer available on SpacePen views."

Please subscribe to commands via `atom.commands.add`:
https://atom.io/docs/api/latest/CommandRegistry#instance-add

Collect the returned subscription objects in a CompositeDisposable:
https://atom.io/docs/api/latest/CompositeDisposable

Call `.dispose()` on your `CompositeDisposable` in this view's `::detached` hook.

Error: The `::command` method is no longer available on SpacePen views."

Please subscribe to commands via `atom.commands.add`:
https://atom.io/docs/api/latest/CommandRegistry#instance-add

Collect the returned subscription objects in a CompositeDisposable:
https://atom.io/docs/api/latest/CompositeDisposable

Call `.dispose()` on your `CompositeDisposable` in this view's `::detached` hook.
  at TextEditorView.$.fn.command (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:584:11)
  at atom-text-editor.<anonymous> (/Users/Andrew/.atom/packages/easy-motion/lib/easy-motion.coffee:25:22)
  at Function.jQuery.extend.each (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:590:23)
  at [object Object].jQuery.fn.jQuery.each (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:237:17)
  at Object.module.exports.activate (/Users/Andrew/.atom/packages/easy-motion/lib/easy-motion.coffee:24:74)
  at Package.module.exports.Package.activateNow (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/package.js:240:19)
  at /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/package.js:742:29
  at Emitter.module.exports.Emitter.emit (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/command-registry.js:227:20)
  at /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/window-event-handler.js:182:20)

```
### Commands

```
  8x -3:07.6 core:backspace (atom-text-editor.editor.is-focused)
     -3:04.3 core:save (atom-text-editor.editor.is-focused)
     -3:04.3 ide-haskell:check-file (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-light-syntax.theme-atom-light-ui)
     -3:04.3 ide-haskell:lint-file (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-light-syntax.theme-atom-light-ui)
     -2:35.5 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -2:35.5 core:cancel (atom-text-editor.editor.is-focused)
  2x -2:34.1 core:move-right (atom-text-editor.editor.is-focused)
     -2:32.3 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -2:32.3 core:cancel (atom-text-editor.editor.is-focused)
     -2:31.8 core:save (atom-text-editor.editor.is-focused)
     -2:31.8 ide-haskell:check-file (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-light-syntax.theme-atom-light-ui)
     -2:31.8 ide-haskell:lint-file (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-light-syntax.theme-atom-light-ui)
  2x -1:59.2 tree-view:toggle (atom-text-editor.editor.is-focused)
  2x -1:50.5 window:toggle-full-screen (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
  2x -1:11.7 core:confirm (atom-text-editor.editor.mini)
     -0:00.6 easy-motion:start (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "atom-light-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
autocomplete-css, v0.4.0
autocomplete-html, v0.3.0
autocomplete-paths, v1.0.2
autocomplete-plus, v2.4.2
easy-motion, v1.1.4
haskell-ghc-mod, v0.4.3
ide-haskell, v0.3.5
language-haskell, v1.0.0

# Dev
No dev packages
```

**Comment by gfarrell** [comment]
+1

**Comment by nieldlr** [comment]
+1 Happened to me as well. Would love be able to use this! :)

**Comment by madhat2r** [comment]
+1

**Comment by DaanDD** [comment]
+1

**Comment by ymatuhin** [comment]
+1

**Comment by alex-vinted** [comment]
+1

**Comment by kWhittington** [comment]
+1

**Comment by ymatuhin** [comment]
+1

**Comment by wjx** [comment]
+1
